export const allPatientList = [
  {
    id: 1,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  { id: 2, lastName: "Lannister", firstName: "Cersei", age: 42 },
  { id: 3, lastName: "Lannister", firstName: "Jaime", age: 45 },
  { id: 4, lastName: "Stark", firstName: "Arya", age: 16 },
  { id: 5, lastName: "Targaryen", firstName: "Daenerys", age: null },
  { id: 6, lastName: "Melisandre", firstName: null, age: 150 },
  { id: 7, lastName: "Clifford", firstName: "Ferrara", age: 44 },
  {
    id: 1,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  {
    id: 1,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  {
    id: 1,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  {
    id: 1,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  {
    id: 1,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  { id: 2, lastName: "Lannister", firstName: "Cersei", age: 42 },
  { id: 3, lastName: "Lannister", firstName: "Jaime", age: 45 },
  { id: 4, lastName: "Stark", firstName: "Arya", age: 16 },
  { id: 5, lastName: "Targaryen", firstName: "Daenerys", age: null },
  { id: 6, lastName: "Melisandre", firstName: null, age: 150 },
  { id: 7, lastName: "Clifford", firstName: "Ferrara", age: 44 },
  { id: 2, lastName: "Lannister", firstName: "Cersei", age: 42 },
  { id: 3, lastName: "Lannister", firstName: "Jaime", age: 45 },
  { id: 4, lastName: "Stark", firstName: "Arya", age: 16 },
  { id: 5, lastName: "Targaryen", firstName: "Daenerys", age: null },
  { id: 6, lastName: "Melisandre", firstName: null, age: 150 },
  { id: 7, lastName: "Clifford", firstName: "Ferrara", age: 44 },
  { id: 2, lastName: "Lannister", firstName: "Cersei", age: 42 },
  { id: 3, lastName: "Lannister", firstName: "Jaime", age: 45 },
  { id: 4, lastName: "Stark", firstName: "Arya", age: 16 },
  { id: 5, lastName: "Targaryen", firstName: "Daenerys", age: null },
  { id: 6, lastName: "Melisandre", firstName: null, age: 150 },
  { id: 7, lastName: "Clifford", firstName: "Ferrara", age: 44 },
];
