export const allPatientList = [
  {
    id: 1,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  { id: 2, lastName: "Lannister", firstName: "Cersei", age: 42 },
  { id: 3, lastName: "Lannister", firstName: "Jaime", age: 45 },
  { id: 4, lastName: "Stark", firstName: "Arya", age: 16 },
  { id: 5, lastName: "Targaryen", firstName: "Daenerys", age: null },
  { id: 6, lastName: "Melisandre", firstName: null, age: 150 },
  { id: 7, lastName: "Clifford", firstName: "Ferrara", age: 44 },
  {
    id: 8,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  {
    id: 9,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  {
    id: 10,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  {
    id: 11,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  {
    id: 12,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  { id: 13, lastName: "Lannister", firstName: "Jaime", age: 45 },
  { id: 14, lastName: "Stark", firstName: "Arya", age: 16 },
  { id: 15, lastName: "Targaryen", firstName: "Daenerys", age: null },
  { id: 16, lastName: "Melisandre", firstName: null, age: 150 },
  { id: 17, lastName: "Clifford", firstName: "Ferrara", age: 44 },
  { id: 18, lastName: "Lannister", firstName: "Cersei", age: 42 },
  { id: 19, lastName: "Lannister", firstName: "Jaime", age: 45 },
  { id: 20, lastName: "Stark", firstName: "Arya", age: 16 },
  { id: 21, lastName: "Targaryen", firstName: "Daenerys", age: null },
  { id: 22, lastName: "Melisandre", firstName: null, age: 150 },
  { id: 23, lastName: "Clifford", firstName: "Ferrara", age: 44 },
  { id: 24, lastName: "Lannister", firstName: "Cersei", age: 42 },
  { id: 25, lastName: "Lannister", firstName: "Jaime", age: 45 },
  { id: 26, lastName: "Stark", firstName: "Arya", age: 16 },
  { id: 27, lastName: "Targaryen", firstName: "Daenerys", age: null },
  { id: 28, lastName: "Melisandre", firstName: null, age: 150 },
  { id: 29, lastName: "Clifford", firstName: "Ferrara", age: 44 },
];

export const deactivePatientList = [
  {
    id: 1,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  { id: 2, lastName: "Lannister", firstName: "Cersei", age: 42 },
  { id: 3, lastName: "Lannister", firstName: "Jaime", age: 45 },
  { id: 4, lastName: "Stark", firstName: "Arya", age: 16 },
  { id: 5, lastName: "Targaryen", firstName: "Daenerys", age: null },
  { id: 6, lastName: "Melisandre", firstName: null, age: 150 },
  { id: 7, lastName: "Clifford", firstName: "Ferrara", age: 44 },
  {
    id: 8,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  {
    id: 9,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  {
    id: 10,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
  {
    id: 11,
    photo: "",
    lastName: "Snow",
    firstName: "MOn",
    age: 35,
    gender: "Male",
    category: "	Gynecology",
    guardian: "RahamtUllah",
    bloodGroup: "O+",
    email: "mdenamahmedchowdhury@gmail.com",
    mobileNo: "018642993619",
  },
];
