export const allScheduleList = [
  {
    id: 1,
    photo: "",
    doctor: "Moniruzaman",
    consultationFees: 350,
    weekday: "Saturday",
    timeStart: new Date(),
    timeEnd: new Date(),
    perPatientDuration: 15,
  },
  {
    id: 2,
    photo: "",
    doctor: "Moniruzaman",
    consultationFees: 350,
    weekday: "Saturday",
    timeStart: new Date(),
    timeEnd: new Date(),
    perPatientDuration: 15,
  },
  {
    id: 3,
    photo: "",
    doctor: "Rubel",
    consultationFees: 350,
    weekday: "Saturday",
    timeStart: new Date(),
    timeEnd: new Date(),
    perPatientDuration: 15,
  },
  {
    id: 4,
    photo: "",
    doctor: "KAmrul",
    consultationFees: 350,
    weekday: "Saturday",
    timeStart: new Date(),
    timeEnd: new Date(),
    perPatientDuration: 15,
  },
  {
    id: 5,
    photo: "",
    doctor: "Rafiq",
    consultationFees: 350,
    weekday: "Saturday",
    timeStart: new Date(),
    timeEnd: new Date(),
    perPatientDuration: 15,
  },
  {
    id: 6,
    photo: "",
    doctor: "Abu Sayeed",
    consultationFees: 350,
    weekday: "Saturday",
    timeStart: new Date(),
    timeEnd: new Date(),
    perPatientDuration: 15,
  },
];
